// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrBnXPdHqM_L5ZYtpBiTU5n5Bpc3DgQc',
    appId: '1:948671370898:web:0b4f348841d391f785b84b',
    messagingSenderId: '948671370898',
    projectId: 'flutter-firebase-masterc-fc0a8',
    authDomain: 'flutter-firebase-masterc-fc0a8.firebaseapp.com',
    storageBucket: 'flutter-firebase-masterc-fc0a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRd4nQER0SPgB8UtJAdbOsKyleiRKem2s',
    appId: '1:948671370898:android:131a0a0d39e84ad785b84b',
    messagingSenderId: '948671370898',
    projectId: 'flutter-firebase-masterc-fc0a8',
    storageBucket: 'flutter-firebase-masterc-fc0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRp_YGmpdTH2bi2G_UvNMAaMe-vsZMkGo',
    appId: '1:948671370898:ios:c5bb859553f9a0b185b84b',
    messagingSenderId: '948671370898',
    projectId: 'flutter-firebase-masterc-fc0a8',
    storageBucket: 'flutter-firebase-masterc-fc0a8.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRp_YGmpdTH2bi2G_UvNMAaMe-vsZMkGo',
    appId: '1:948671370898:ios:c5bb859553f9a0b185b84b',
    messagingSenderId: '948671370898',
    projectId: 'flutter-firebase-masterc-fc0a8',
    storageBucket: 'flutter-firebase-masterc-fc0a8.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHrBnXPdHqM_L5ZYtpBiTU5n5Bpc3DgQc',
    appId: '1:948671370898:web:d497d08f5aea172785b84b',
    messagingSenderId: '948671370898',
    projectId: 'flutter-firebase-masterc-fc0a8',
    authDomain: 'flutter-firebase-masterc-fc0a8.firebaseapp.com',
    storageBucket: 'flutter-firebase-masterc-fc0a8.appspot.com',
  );
}
